pipeline{
    agent {
        docker { 
            image 'maven:3.9.7-eclipse-temurin-17-alpine'
            args '-u "$(id -u):$(id -g)" -v $HOME/.m2:/var/maven/.m2:z -e MAVEN_CONFIG=/var/maven/.m2 -e MAVEN_OPTS="-Duser.home=/var/maven"'
            //args '-v /home/jenkins/.m2:/home/jenkins/.m2:z -e MAVEN_CONFIG=/var/maven/.m2 -e MAVEN_OPTS="-Duser.home=/var/maven"'
            reuseNode true
        }
    }

    
    stages {

        stage('Checkout') {
            steps {
                script {
                    checkout scm
                }
            }
        }


        stage('Check user privileges') {
            steps {
                script {
                    sh 'whoami'
                    sh 'id -u'
                    sh 'id -g'
                    sh 'echo $HOME'
                    sh 'ls -al --recursive /var/maven/'
                }
            }
        }

        stage('Build and Test') {
            steps {
                script {
                    sh 'mvn -B clean package -DskipTests'
                }
            }
        }

        stage('Clean up') {
            steps {
                deleteDir()
            }
        }
    }   
}