pipeline{
    agent {
        docker { 
            image 'maven:3.9.7-eclipse-temurin-17-alpine' 
            //args '-u root'
            //args '-v $HOME/.m2:/var/maven/.m2:z -e MAVEN_CONFIG=/var/maven/.m2 -e MAVEN_OPTS="-Duser.home=/var/maven"'
        }
    }

    
    stages {

        stage('Checkout') {
            steps {
                script {
                    checkout scm
                }
            }
        }

        stage('Build and Test') {
            steps {
                script {
                    sh 'mvn -B clean package -DskipTestss'
                }
            }
        }

        stage('Clean up') {
            steps {
                deleteDir()
            }
        }
    }   
}